### ISSUE TITLE
下载了空白文件

### ISSUE THREAD

**Issue by Qinnne** [imputnet/cobalt#1245]
### bug description

![Image](https://github.com/user-attachments/assets/7a493d60-7546-4de0-a3d9-c40cb0e38686)

### reproduction steps

多次尝试都是如此。

### links

```shell

```

### platform information

Windows11 22H2 Microsoft Edge 136.0.3240.37 (正式版本) beta (64 位)

**Comment by dumbmoron** [comment]
我不会说中文。

**Comment by wukko** [comment]
should be fixed now, try again

**Comment by Qinnne** [comment]
> 我不会说中文。

Sometimes when I download a file, it ends up being totally blank with nothing inside. I've tried downloading it several times, but it still doesn't work, and it's really frustrating.

**Comment by Qinnne** [comment]
> should be fixed now, try again

Thanks
