### ISSUE TITLE
Can't download videos from YouTube on cobalt.tools

### ISSUE THREAD

**Issue by wukko** [imputnet/cobalt#1356]
youtube seems to have changed something on their side, and the main instance can't access videos anymore. specifically, 90% of requests to googlevideo on both iOS and WEB_EMBEDDED client return 403. some requests do go through, but it's rare.

we're already looking into a way to fix this, and will post and update here and on twitter whenever it happens!

cobalt will show this error as long as this issue is present:

<img width="449" alt="Image" src="https://github.com/user-attachments/assets/26b8aa7d-3e7f-4506-8ed7-2eb221f27d1f" />

please **DON'T** make duplicate issues and don't reply with "me too". it affects everyone on the main instance, including you.

you can follow notifications for this issue here:
<img width="290" alt="Image" src="https://github.com/user-attachments/assets/04d2930c-4f3b-401d-8782-007e81db4c67" />

**Comment by maxcomperatore** [comment]
im shaking and crying rn im devastated fr

edit: bro fix it it's been 81 days ong

**Comment by 2shiraz** [comment]
Apparently, youtube blocked the whole subnet of my proxy servers. i was using ipv6 blocks which is blocked up to /40 ips. i guess changing proxy/cloud providers for me is the solution.

**Comment by regedit-sys** [comment]
i think we SHOULD make duplicate issues and reply with "me too"!
okay, but seriously, google is so annoying sometimes. we need to start a movement

**Comment by Intercity225** [comment]
In the meantime is there any alternatives?

**Comment by wukko** [comment]
> In the meantime is there any alternatives?

https://github.com/yt-dlp/yt-dlp

**Comment by Intercity225** [comment]
Thank you, and hoping it's solved promptly!

**Comment by ledsales** [comment]
> In the meantime is there any alternatives?

I just installed JDownloader 2 as a backup until Cobalt is online, it works fine, interface is a bit meh because it grabs everything, not just the vid, but audio streams, images etc, so you have to turn those off. I also haven't found how to make it stop creating subfolders, even for a single video file. But aside from those issues, which are probably me needing more time to play with the interface, it seems to be a good alternative and very quick to download vids.

**Comment by JoaoFelipe3** [comment]
aw dangit can't download sonic cd soundtrack now can i 😭

**Comment by G1tR4kt** [comment]
> In the meantime is there any alternatives?

Ive been downloading from yt for years with random sites, they ALL stopped working last year, i think you would have to wait until cobalt figures it out, its the only way currently i guess

**Comment by MrCoreyTys** [comment]
This is truly mayhem. I'm sure why YouTube is doing this is to promote YT Premium instead of letting people use other video downloaders like Cobalt, I think that's it.

**Comment by andyfoxmsconfig** [comment]
Cobalt is still down, doesn't work
Also of the alternatives to it, whilst it's having seizure due to Google blocking some APIs is:
[ https://en.loader.to/4/ ]

**Comment by pansy4life** [comment]
Is there any ETA on when this could be fixed?

**Comment by masterconfig** [comment]
Are there any news regarding the project's current state? ;-;

**Comment by dumbmoron** [comment]
> Are there any news regarding the project's current state? ;-;

@andyfoxmsconfig  the project is not dead, everything other than youtube still works. if there were any updates, we would post them here (amongst other places)

**Comment by dumbmoron** [comment]
self hosted instances are not affected by this, so if you need it to work urgently you could also host your own instance, we have instructions on how to set it up [here](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md)

**Comment by MatthewSH** [comment]
> self hosted instances are not affected by this, so if you need it to work urgently you could also host your own instance, we have instructions on how to set it up [here](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md?rgh-link-date=2025-06-22T18%3A24%3A36.000Z)

This, from my testing, is only true if you're on residential IPs or not flagged IPs. My self-hosted instance is impacted because it requires yt-session-generator and keeps throwing the YouTube login error which it hadn't prior.

**Comment by wukko** [comment]
> keeps throwing the YouTube login error which it hadn't prior

then your ip address probably got blocked by youtube. there’s no way around it aside from using account cookies (not recommended, they also tend to get blocked) or using a different ip address :(

**Comment by rupertgti** [comment]
You could self-hosted a cobalt-api and cobalt-web at this moment, if you have a regional block for example like my case....

I use this easy docker-compose, I reference the sources of this:

```
#https://github.com/imputnet/cobalt/blob/main/docs/examples/docker-compose.example.yml
services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:11
    init: true
    read_only: true
    network_mode: "bridge"
    restart: unless-stopped
    container_name: cobalt-api
    ports:
      - 9000:9000/tcp
      # if you use a reverse proxy (such as nginx),
      # uncomment the next line and remove the one above (9000:9000/tcp):
      # - 127.0.0.1:9000:9000

    environment:
      # replace https://api.url.example/ with your instance's url
      # or else tunneling functionality won't work properly
      API_URL: "http://YOUR_IP:9000"
      # if you want to use cookies for fetching data from services,
      # uncomment the next line & volumes section
      # COOKIE_PATH: "/cookies.json"
      # it's recommended to configure bot protection or api keys if the instance is public,
      # see /docs/protect-an-instance.md for more info
      # see /docs/run-an-instance.md for more variables that you can use here

#custom project:
#https://github.com/imputnet/cobalt/issues/768
#https://github.com/NotNite/cobalt-web-docker

  cobalt-web:
    container_name: cobalt-web
    network_mode: "bridge"
    restart: unless-stopped
    build:
      context: https://github.com/NotNite/cobalt-web-docker.git
      dockerfile: Dockerfile
      additional_contexts:
        cobalt-src: https://github.com/imputnet/cobalt.git

      args:
        WEB_HOST: "http://YOUR_IP:9001/"
        WEB_DEFAULT_API: "http://YOUR_IP:9000/"

    ports:
      - 9001:3000/tcp

```

**Comment by Notaroror** [comment]
Is there an estimated time we'll see this fixed, i want to not have to use shady websites.

**Comment by gitboiaa1** [comment]
> Is there an estimated time we'll see this fixed, i want to not have to use shady websites.

use yt-dlp until Cobalt is fixed, but its a bit confusing as it needs the windows console

**Comment by mgytr** [comment]
I have my own instance, if someone wants it, kindly message me on Telegram or Discord. But don't download a lot please.

**Comment by Andy-Mckelvey05** [comment]
> self hosted instances are not affected by this, so if you need it to work urgently you could also host your own instance, we have instructions on how to set it up [here](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md)

what version do we host for this?
i have mine running locally but i still cant download Youtube locally
Something about 'libav-6.5.7.1-remux-cli.thr.mjs' not existing idk :(

**Comment by mgytr** [comment]
> > self hosted instances are not affected by this, so if you need it to work urgently you could also host your own instance, we have instructions on how to set it up [here](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md)
> 
> what version do we host for this? i have mine running locally but i still cant download Youtube locally Something about 'libav-6.5.7.1-remux-cli.thr.mjs' not existing idk :(

Use [this](https://github.com/imputnet/cobalt/issues/1356#issuecomment-2995278422)

**Comment by wukko** [comment]
main instance is able to download videos from youtube again!

we also released the 11.2 update with some cool features: https://cobalt.tools/updates#11.2

**Comment by slittle95** [comment]
are you sure

![Image](https://github.com/user-attachments/assets/c3d8eba5-f62c-475b-8077-96fa90bb9a69)

getting the "youtube asked the instance to prove it's not a bot" error repeatedly, should I report it as a new issue or is it part of this one?

**Comment by dobkun** [comment]
it still shows the the for me 

![Image](https://github.com/user-attachments/assets/5dc08b49-cee3-4f1f-8505-513ceb3e487e)

**Comment by slittle95** [comment]
@dobkun @dumbmoron I think we're following 1375 for this now https://github.com/imputnet/cobalt/issues/1375

**Comment by squabbled** [comment]
> How do other sites still work then?

@MatthewSH It’s because YouTube is the one doing the blocking intentionally. Other sites aren’t as aggressive in trying to block downloading tools and websites as YouTube is. If you mean how other downloading tools work, it’s likely because YouTube hasn’t tried blocking them yet and they’ve flown under the radar, or in the case of YT-DLP, it uses your connection so all YouTube sees is a signed out user.

**Comment by TheOnlyOnlyName** [comment]
Ah interesting, well at least there are other options. Cobalt is amazing except when it isn't 🥲
In terms of being signed out I haven't tested yt dlp though but it's interesting, I've started getting an error saying I need to sign in when watching videos in incognito on my home IP, and a captcha once in a VPN, hopefully that isn't causing yt dlp issues.

**Comment by LolproDoesStuff** [comment]
I found an alternative website some days ago, it's literally cobalt but it runs on a community instance, it works perfectly and youtube still works.
you can try it out here: [https://cobalt.meowing.de/](https://cobalt.meowing.de/)

**Comment by fleetimee** [comment]
> I found an alternative website some days ago, it's literally cobalt but it runs on a community instance, it works perfectly and youtube still works. you can try it out here: [cobalt.meowing.de](https://cobalt.meowing.de/)

Thanks

**Comment by carpaltunnelsurgery** [comment]
(commenting again because i sent in wrong thread)

i was working on a possible fix and found that it could be consistently bypassed with tor

not sure if you guys have already tried it, but routing it through tor bypasses the login wall most of the time

this package may be of use: https://www.npmjs.com/package/tor-request

**Comment by gablilli** [comment]
> (commenting again because i sent in wrong thread)

I don't know if that's true, I think that [this](https://github.com/imputnet/cobalt/issues/1375) thread is more monitored, so yeah.. why not send it there.

**Comment by The2AndOnly** [comment]
It's still happening! Every other YouTube converter website works so I've been forced to go to those shady sites that don't give the highest quality.

**Comment by python-nerd-3** [comment]
> It's still happening! Every other YouTube converter website works so I've been forced to go to those shady sites that don't give the highest quality.

use cobalt.meowing.de

**Comment by HU1212ICAN3** [comment]
Yeah pretty much every other site still works so idk why its an issue. I DMed Wukko but no reply so sounds like this is just abandoned. And that SUCKS because i really like this site. Mostly because it feels very old school like it was from the 2000s. Gonna suck if this doesnt get resolved.

**Comment by wukko** [comment]
as mentioned in the issue, don’t spam this issue unless it’s something useful

**Comment by MatthewSH** [comment]
> but no reply so sounds like this is just abandoned

I don't know if this is considered off topic, but as stated in the update on the OP YouTube has implemented some strict ways of blocking services like Cobalt. Other sites may work but inevitably will get blocked in the future. This is not unique to Cobalt. You'd have to use it locally with things like yt-dlp but that requires some more hands on work. Cobalt isn't abandoned (you can see from the commits it's still active), just the YouTube portion of it is not working at this time.

They even share this information on Twitter: https://x.com/justusecobalt/status/1943279590178230618

Cobalt still is active and supports a lot of services. If you want to try to help get YouTube back online, I'm sure they would love some ideas to fix it. :) (lord knows I'm not smart enough for that)

**Comment by HU1212ICAN3** [comment]
> as mentioned in the issue, don’t spam this issue unless it’s something useful

Your discord doesnt have a general chat. Sorry idk where else to get information and i dont use twitter.

**Comment by MatthewSH** [comment]
> > as mentioned in the issue, don’t spam this issue unless it’s something useful
> 
> Your discord doesnt have a general chat. Sorry idk where else to get information and i dont use twitter.

You can subscribe to issue updates here on GitHub, @HU1212ICAN3, which will show up in your inbox here on the site and in your email (if configured). 

<img width="358" height="159" alt="Image" src="https://github.com/user-attachments/assets/7e928b40-c1de-45d5-a59f-a9de1935752d" />

You can also periodically check the original post: https://github.com/imputnet/cobalt/issues/1356#issue-3161002795

It looks like wukko updates it as more information is available. There are options available if you're just looking for updates.

**Comment by SpareEnderboy** [comment]
just another day of youtube trying to get you to buy youtube premium...

**Comment by ungaul** [comment]
Couldn't we just use YouTube cookies as YT-DLP does?

**Comment by spencermacca** [comment]
> as mentioned in the issue, don’t spam this issue unless it’s something useful

this is lowkey such a silly thing to say. guy is giving a solution to the problem for 99% of people who end up on this thread. 

if youtube downloading is going to be broken for as long as it has been, why not give people some alternatives on the popup instead of it just being this message saying "it's broken rn"

without a doubt, cobalt is by far one of my favourite youtube downloaders of all time it's the goat but plz just make the solution to most people's problems obvious 🙏

**Comment by MatthewSH** [comment]
> if youtube downloading is going to be broken for as long as it has been, why not give people some alternatives on the popup instead of it just being this message saying "it's broken rn"

It's been mentioned before about YT-DLP @spencermacca. Any recommendation from the Cobalt team would be seen as them supporting or pushing people to a product and if that product turns out poorly or unsafe for users the blame falls back on the Cobalt team which impacts their reputation.

YT-DLP is the only truly "safe" at the moment but still has it's risks, of course.

**Comment by squabbled** [comment]
> Couldn't we just use YouTube cookies as YT-DLP does?

YouTube rate limits accounts too. On yt-dlp it's less noticeable as you're the only person downloading compared to Cobalt which has millions of people downloading from one server. I've had yt-dlp cookies be revoked and rate limited and had to make several YouTube accounts for bulk downloads. It's not practical for a larger operation like Cobalt to have a surplus of accounts as they'd burn through them extremely fast and cause errors and trouble for users.

**Comment by squabbled** [comment]
> > if youtube downloading is going to be broken for as long as it has been, why not give people some alternatives on the popup instead of it just being this message saying "it's broken rn"
> 
> It's been mentioned before about YT-DLP [@spencermacca](https://github.com/spencermacca). Any recommendation from the Cobalt team would be seen as them supporting or pushing people to a product and if that product turns out poorly or unsafe for users the blame falls back on the Cobalt team which impacts their reputation.
> 
> YT-DLP is the only truly "safe" at the moment but still has it's risks, of course.

For what it's worth, Cobalt is still "safe" and reliable at fetching YouTube streams, albeit YouTube has just gone after the main instance and some community instances. Self-hosting is still very much an option, Cobalt lets you use your own backend. I've found that regular home internet connections are often more reliable for downloading too, which is another perk of self-hosting it for yourself. There's more than just yt-dlp, and Cobalt will still download videos fine. Just public instances and high frequency downloaders that are affected, unfortunately.

**Comment by MatthewSH** [comment]
> There's more than just yt-dlp, and Cobalt will still download videos fine. Just public instances and high frequency downloaders that are affected, unfortunately.

Thanks for that correction! I forgot to mention it because it hasn't worked for me very much, for some reason my IPs are flagged easier but I digress.

**Comment by squabbled** [comment]
> for some reason my IPs are flagged easier but I digress.

For what it's worth, I've found data center (VPSes, cloud servers, VPNs) IPs get blocked quickly or are often blocked entirely before even accessing YouTube. If you can get a household IP from an internet provider like Comcast or Spectrum (at least here in the states, dVPNs exist) you would likely have better luck. You can also make a burner YouTube account if it's just you and/or a few friends using it to avoid this altogether. I have 1 burner account I use for yt-dlp and it's worked fine for bulk downloads under 300 per day.

**Comment by meowgoober** [comment]
sdiybt🥀

**Comment by gablilli** [comment]
> sdiybt🥀

we are NOT on tiktok bro.

**Comment by DarkBlu242** [comment]
> sdiybt🥀

yk like a 100 people get a email everytime you comment here🥀

**Comment by superdave938** [comment]
true...
