### ISSUE TITLE
[Twitter] error.api.fetch.empty on age-restricted content

### ISSUE THREAD

**Issue by fclivaz42** [imputnet/cobalt#1419]
### bug description

After setting my cookies for the twitter service on a self-hosted instance, i still am unable to fetch age-restricted content, being greeted with `error.api.fetch.empty`.
I have set my cookies in the cookies.json file and i know they are being loaded because i set a dummy cookie for a site that doesn't exist and the console shows me that it ignored that unknown service. I have tried to only set ct0 and auth_token or *all* of the available cookies, with no avail.

### reproduction steps

1. set cookies in cookies.json with the data of account that has access to age-restricted content
2. attempt to fetch a link that is considered age-restricted (eg. https://twitter.com/coderonex/status/1954811243606184133)
3. a wild `api.error.fetch.empty` appears!

### screenshots

<img width="793" height="290" alt="Image" src="https://github.com/user-attachments/assets/cbd73265-c7e4-4b0e-8458-d5daa56fce7b" />

<img width="990" height="180" alt="Image" src="https://github.com/user-attachments/assets/8c695aa2-1e8b-454e-83c3-7f3730e940be" />

### links

```shell
https://twitter.com/coderonex/status/1954811243606184133
```

### platform information

self-hosted instance (11.4.1, docker container freshly pulled)

**Comment by abishek77s** [comment]
The link works on the live website without any issue, did you provide the right link because it was a simple SFW animation.

**Comment by dumbmoron** [comment]
this was likely resolved by #1436

**Comment by fclivaz42** [comment]
> this was likely resolved by [#1436](https://github.com/imputnet/cobalt/pull/1436)

Just as a clarification: which are the *necessary* cookies for Coblat to run properly? I would like to try again (still getting `error.api.fetch.empty`) and report results properly.


> The link works on the live website without any issue, did you provide the right link because it was a simple SFW animation.

I did! I tried it personally as well, opening in an icognito tab resulted in Twitter saying that the link did not exist. Using my logged account worked, though. Yet self-hosted Cobalt resulted in the error. It is a SFW animation but it somehow got recognized as age-restricted?

**Comment by fclivaz42** [comment]
Hello again @dumbmoron . This issue hasnt been solved since that day and even though the main cobalt.tools website works properly, trying to pull links twitter considers 18+ (which includes art references id like to save...) through a self-hosted instance ends up in the `api.fetch.empty` error i mentionned.

I set the `auth_token` and `ct0` variables in cookie.json just like the docs and yet I am getting the `api.fetch.empty`.

<img width="787" height="242" alt="Image" src="https://github.com/user-attachments/assets/82daaa20-ba3f-46d5-9d42-6ba9f56e1f19" />

this is what opening the link i sent above ( https://twitter.com/coderonex/status/1954811243606184133 ) does. So twitter considers it 18+.

<img width="908" height="72" alt="Image" src="https://github.com/user-attachments/assets/f9807270-9605-4858-88f9-8449ad784ce9" />

Yet trying to pull it from the self-hosted instance (v11.5) results in the error I mentionned, as shown above (command truncated to hide API key).

I genuinely have NO idea what I am doing wrong or what is happening (because if i recall correctly cobalt used the proper age restricted error back then?) hence why I am here.

**Comment by fclivaz42** [comment]
Update: Somehow it's fixed now.
