### ISSUE TITLE
Failed to extract signature decipher algorithm [YouTube]

### ISSUE THREAD

**Issue by bandicuttt** [imputnet/cobalt#991]
### problem description

When trying to download any video or shorts from youtube I get this error
```
[YOUTUBEJS][Player]: Failed to extract signature decipher algorithm.
```

Ran it on different platforms

**Comment by nicolaigaina** [comment]
having the same issue when I run cobat api instance locally

**Comment by wukko** [comment]
this error doesn’t affect cobalt as it doesn’t decipher anything. it’s fixed in the dev branch and will be merged soon!

**Comment by bandicuttt** [comment]
just wanted to write that yt-dlp has already rolled out the update. Waiting for the merge

**Comment by jo-chemla** [comment]
Issue is still present on latest cobalt 7 docker image: `image: ghcr.io/imputnet/cobalt:7`
Would it be possible to apply the yt-dlp update to cobalt api v7 as well? Thanks!

**Comment by wukko** [comment]
> Would it be possible to apply the yt-dlp update to cobalt api v7 as well

cobalt doesn’t use yt-dlp, and v7 is no longer supported. i advise you to move to v10 and future latest releases

**Comment by jo-chemla** [comment]
I cannot switch to v10 because I need a fully self-hosted cobalt, not only the instance but the frontend as well - see here https://github.com/imputnet/cobalt/issues/722 and there https://github.com/imputnet/cobalt/issues/768

Seems that the simple fix is to update cobalt v7 `package.json` so the inimum required youtubei.js version starts from [`YouTube.js/releases/tag/v12.1.0` ](https://github.com/LuanRT/YouTube.js/releases/tag/v12.1.0) onwards, released on Dec 10 2024 with fix `Fix signature algorithm extraction` as shown in this thread https://github.com/LuanRT/YouTube.js/issues/831

**Comment by jo-chemla** [comment]
Thanks for the feedback, understood - sad given how simple the fix is, but it might indeed introduce breaking changes which would incur more than just the version bump. 

The general consensus around v10 in the referenced issues seems to be that most self-hosters that had a working docker-compose setup on v7 won't switch unless there are built images available to ghrc/docker-hub or any other image repo that makes it as easy to deploy, without requiring to build the image one-self. 

But thanks for pointing towards these instructions!

**Comment by twicer-is-coder** [comment]
This is happening again since 24 March. v13.2.0.
